### ISSUE TITLE
feature: Transcribe audios to text

### ISSUE THREAD

**Issue by totallynotdavid** [totallynotdavid/WhatsAppBot#19]

**Comment by totallynotdavid** [comment]
Tried:
- https://github.com/mozilla/DeepSpeech-examples/blob/r0.9/nodejs_wav/Readme.md it doesn't work with node > 16 and I'm using node 20!
- https://github.com/akashmjn/tinydiarize is an interesting approach with annotations but only english was finetuned! not our current use case.

**Comment by totallynotdavid** [comment]
- https://github.com/ChetanXpro/nodejs-whisper causes this issue:

```
filePath:  /workspaces/nodejs-whisper/audio/holmes.wav
[Nodejs-whisper] Models already exist. Skipping download.
[Nodejs-whisper]  Executing command: ./main  -otxt -ovtt -osrt -ml 1 -sow true  -l auto -m ./models/ggml-base.en.bin  -f /workspaces/nodejs-whisper/audio/holmes.wav  


[Nodejs-whisper] Transcribing Done!
[Transcription service] Error:  Error: Something went wrong while executing the command.
    at /workspaces/nodejs-whisper/node_modules/nodejs-whisper/src/index.ts:39:9
    at Generator.next (<anonymous>)
    at fulfilled (/workspaces/nodejs-whisper/node_modules/nodejs-whisper/dist/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
/workspaces/nodejs-whisper/node_modules/nodejs-whisper/dist/index.js:5
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
Error: Something went wrong while executing the command.
    at /workspaces/nodejs-whisper/node_modules/nodejs-whisper/src/index.ts:39:9
    at Generator.next (<anonymous>)
    at fulfilled (/workspaces/nodejs-whisper/node_modules/nodejs-whisper/dist/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by totallynotdavid** [comment]
Tested on:
- https://github.com/SYSTRAN/faster-whisper
- https://github.com/openai/whisper

It takes too long to process and uses too much resources, I don't find it suitable for our use cases. There should be better methods for audio-to-text.
